api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "areapro-cart-transform"
type = "function"
uid = "a92952bf-7276-0e8c-7235-d1109558c4ffd6fc57a3"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
